#spring:
#  datasource:
#    username: root
#    password: cl3cl3j06j06
#    url: jdbc:mysql://${MYSQL_HOST:localhost}:1993/GamersUp
#    driver-class-name: com.mysql.cj.jdbc.Driver
#  jpa:
#    show-sql: true
#    hibernate:
#      ddl-auto: update
#